name: Python Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install Hatch
        run: pip install hatch

      - name: Build the Wheel and Source Distribution
        run: hatch build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
